### ISSUE TITLE
软件用cmd打开后命令无效。

### ISSUE THREAD

**Issue by yyyaxuan** [ne1llee/xbsrebuild#1]
Microsoft Windows [版本 10.0.23550.1000]
(c) Microsoft Corporation。保留所有权利。

D:\Program Files\xbsrebuild-windows>xbsrebuild-windows-amd64.exe
A brief description of your application

Usage:
  xbsrebuild [command]

Available Commands:
  completion  Generate the autocompletion script for the specified shell
  help        Help about any command
  json2xbs    json to xbs
  server      server
  xbs2json    xbs to json

Flags:
  -h, --help     help for xbsrebuild
  -t, --toggle   Help message for toggle

Use "xbsrebuild [command] --help" for more information about a command.

D:\Program Files\xbsrebuild-windows>xbsrebuild [command] --help
'xbsrebuild' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

xbsrebuild-windows-386.exe也是一样，添加环境变量也没用。win11系统。

**Comment by ne1llee** [comment]
第一次不是已经运行成功了吗 输出信息里面都提示你需要带参数运行
xbsrebuild-windows-amd64.exe  xbs2json -i 需要解密的xbs文件路径 -o 解密完成后json的保存路径

**Comment by ne1llee** [comment]
还可以运行命令 xbsrebuild-windows-amd64.exe server  打开web服务后，浏览器访问http://127.0.0.1:8282

**Comment by yyyaxuan** [comment]
> 第一次不是已经运行成功了吗 输出信息里面都提示你需要带参数运行 xbsrebuild-windows-amd64.exe xbs2json -i 需要解密的xbs文件路径 -o 解密完成后json的保存路径

我的问题，不懂代码的小白。以为”xbsrebuild“就是命令开头了。现在知道了是用”xbsrebuild-windows-xxx.exe“。
剩下就都会了，谢谢大佬。
